import React, { useState } from "react";
import { useAppContext } from "../context/AppContext";

const EXAMPLES = ["A quiet beach stay with breakfast under $250", "A central London room for a foodie weekend", "Luxury pool hotel for two in Dubai"];

const AISmartSearch = () => {
  const { axios, navigate, currency } = useAppContext();
  const [query, setQuery] = useState(""); const [results, setResults] = useState([]); const [interpretation, setInterpretation] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const search = async (event) => { event.preventDefault(); if (!query.trim()) return; setLoading(true); setMessage(""); setResults([]); try { const { data } = await axios.post("/api/ai/smart-search", { query: query.trim() }); if (data.success) { setResults(data.rooms || []); setInterpretation(data.interpretation || "Here are the strongest matches from our stays."); if (!data.rooms?.length) setMessage("No exact match yet. Try changing the destination, budget, or vibe."); } else setMessage(data.message || "Smart Search is unavailable right now."); } catch { setMessage("Smart Search is unavailable right now."); } finally { setLoading(false); } };
  return <section id="smart-search" className="px-4 md:px-16 lg:px-24 xl:px-32 py-16 md:py-20 bg-slate-50"><div className="max-w-5xl mx-auto"><div className="text-center mb-7"><span className="inline-flex items-center gap-1 bg-sky-100 text-sky-700 text-xs font-semibold px-3 py-1 rounded-full mb-3">AI SMART SEARCH</span><h2 className="text-2xl md:text-4xl font-playfair">Describe the stay you want</h2><p className="text-gray-500 mt-2 text-sm md:text-base">No filters. Tell TravelWithAsh what you are looking for in your own words.</p></div><form onSubmit={search} className="bg-white border border-slate-200 rounded-2xl shadow-sm p-3 flex flex-col sm:flex-row gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} className="flex-1 min-w-0 px-3 py-2.5 outline-none text-sm" placeholder="Try: romantic pool stay in Dubai under $300" /><button disabled={loading || !query.trim()} className="bg-slate-900 hover:bg-sky-700 disabled:opacity-50 text-white rounded-xl px-5 py-2.5 text-sm font-medium shrink-0">{loading ? "Searching…" : "Ask AI"}</button></form><div className="flex flex-wrap justify-center gap-2 mt-4">{EXAMPLES.map((example) => <button key={example} onClick={() => setQuery(example)} className="text-xs px-3 py-1.5 rounded-full bg-white border border-slate-200 text-slate-600 hover:border-sky-400">{example}</button>)}</div>{(interpretation || message) && <p className="text-center text-sm text-slate-600 mt-7">{message || interpretation}</p>}{results.length > 0 && <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 mt-7">{results.map((room) => <article key={room._id} className="rounded-2xl overflow-hidden bg-white border border-slate-200 shadow-sm"><img src={room.images?.[0]} alt={`${room.hotel?.name} ${room.roomType}`} className="w-full h-40 object-cover" /><div className="p-4"><p className="font-playfair text-lg">{room.hotel?.name}</p><p className="text-sm text-gray-500">{room.hotel?.city} · {room.roomType}</p><p className="mt-2 text-sky-700 font-semibold">{currency}{room.pricePerNight} <span className="text-xs font-normal text-gray-500">/ night</span></p><div className="flex flex-wrap gap-1 mt-3">{room.amenities?.slice(0, 3).map((amenity) => <span key={amenity} className="text-[11px] bg-slate-100 px-2 py-1 rounded-full">{amenity}</span>)}</div><button onClick={() => { navigate(`/rooms/${room._id}`); window.scrollTo(0, 0); }} className="mt-4 w-full py-2 rounded-lg bg-slate-900 text-white text-sm hover:bg-sky-700">View stay</button></div></article>)}</div>}</div></section>;
};
export default AISmartSearch;
